version: '3.4'

services:
  basketdb:
    image: mongo:latest
    container_name: basketdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - 'db_data:/data/db'
      - 'db_config:/data/configdb'
    networks:
      - db-net
    ports:
      - 27017:27017
  basketservice:
    image: ${DOCKER_REGISTRY-}basketservice
    build:
      context: .
      dockerfile: BasketService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:49155
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString="mongodb://test:test@basketdb:27017",
      - DatabaseName="BasketDb",
    ports:
      - "49155:49155"
    depends_on:
      - basketdb
    networks:
      - db-net
      - backend-net

networks:
  db-net:
  backend-net:

volumes:
  db_data:
    driver: local
  db_config:
    driver: local